http:
    middlewares:
        redirect:
            redirectScheme:
                scheme: https

tls:
    stores:
        default:
            defaultCertificate:
                certFile: /certs/localhost.pem
                keyFile: /certs/localhost-key.pem
    certificates:
        - certFile: /certs/localhost.pem
          keyFile: /certs/localhost-key.pem

providers:
    file:
        filename: /config.yml
        watch: true
    docker:
        exposedByDefault: false
        network: casker_backend
