version: '3.7'

networks:
    backend:
        name: casker_backend
        external: true

volumes:
    neo4j-storage:
        name: local-neo4j-data

services:
    reverse-proxy:
        image: traefik:v2.2
        networks:
            - backend
        ports:
            - "80:80" 
            - "443:443" 
            - "8080:8080" 
        command:
            # CLI
            ## API  
            - --api.dashboard=true
            - --api.debug=true
            ## Log settings
            - --log.level=DEBUG
            ## provider settings
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --providers.file.filename=/config.yml
            - --providers.docker.network=casker_backend
            ## entrypoints
            - --entrypoints.web.address=:80
            - --entrypoints.web-secured.address=:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config.yml:/config.yml
            - ./certs:/certs
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`monitor.localhost`)"
            - "traefik.http.routers.api.service=api@internal"
    neo4j:
        image: neo4j:latest
        networks:
            - backend
        ports:
            - "7474:7474"
            - "7687:7687"
        labels:
            - "traefik.enable=true"
            
            - "traefik.http.services.neo4j.loadbalancer.server.port=7474"
            
            - "traefik.http.routers.neo4j.service=neo4j"
            - "traefik.http.routers.neo4j.rule=Host(`neo4j.localhost`)"
            - "traefik.http.routers.neo4j.entrypoints=web"
            - "traefik.http.routers.neo4j.middlewares=redirect@file"

            - "traefik.http.routers.neo4j-secured.service=neo4j"
            - "traefik.http.routers.neo4j-secured.rule=Host(`neo4j.localhost`)"
            - "traefik.http.routers.neo4j-secured.entrypoints=web-secured"
            - "traefik.http.routers.neo4j-secured.tls=true"
            
              # database
            - "traefik.http.services.neo4jdb.loadbalancer.server.port=7687"

            - "traefik.http.routers.neo4jdb.service=neo4jdb"
            - "traefik.http.routers.neo4jdb.rule=Host(`neo4jdb.localhost`)"
            - "traefik.http.routers.neo4jdb.entrypoints=web"
            - "traefik.http.routers.neo4jdb.middlewares=redirect@file"
            
            - "traefik.http.routers.neo4jdb-secured.service=neo4jdb"
            - "traefik.http.routers.neo4jdb-secured.rule=Host(`neo4jdb.localhost`)"
            - "traefik.http.routers.neo4jdb-secured.entrypoints=web-secured"
            - "traefik.http.routers.neo4jdb-secured.tls=true"

            ## tcp
            - "traefik.tcp.services.neo4jdb.loadbalancer.server.port=7687"

            - "traefik.tcp.routers.neo4jdb.service=neo4jdb"
            - "traefik.tcp.routers.neo4jdb.rule=HostSNI(`neo4jdb.localhost`)"
            - "traefik.tcp.routers.neo4jdb.tls=true"
        volumes:
            - neo4j-storage:/data
        environment:
            - NEO4J_AUTH=neo4j/admin
