version: '3.7'

networks:
    backend:
        name: proof_backend
        external: true

volumes:
    neo4j-storage:
        name: local-neo4j-data
    postgres-storage:
        name: local-postgres-data
    elastisearch-storage:
        name: local-es-data
    fa-configs:
        name: local-fa-data

services:
    reverse-proxy:
        image: traefik:v2.2
        networks:
            - backend
        ports:
            - "80:80" 
            - "443:443" 
            - "8080:8080" 
        command:
            # CLI
            ## API  
            - --api.dashboard=true
            - --api.debug=true
            ## Log settings
            - --log.level=DEBUG
            ## provider settings
            - --providers.docker=true
            - --providers.docker.exposedByDefault=false
            - --providers.file.filename=/config.yml
            - --providers.docker.network=proof_backend
            ## entrypoints
            - --entrypoints.web.address=:80
            - --entrypoints.web-secured.address=:443
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./config.yml:/config.yml
            - ./certs:/certs
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api.rule=Host(`monitor.proof.localhost`)"
            - "traefik.http.routers.api.service=api@internal"
            - "traefik.http.routers.api.middlewares=redirect@file"

            - "traefik.http.routers.api-secured.service=api@internal"
            - "traefik.http.routers.api-secured.rule=Host(`monitor.proof.localhost`)"
            - "traefik.http.routers.api-secured.entrypoints=web-secured"
            - "traefik.http.routers.api-secured.tls=true"
    neo4j:
        image: neo4j:4.0
        networks:
            - backend
        ports:
            - "7687:7687"
        labels:
            - "traefik.enable=true"
            
            - "traefik.http.services.neo4j.loadbalancer.server.port=7474"

            - "traefik.http.routers.neo4j.service=neo4j"
            - "traefik.http.routers.neo4j.rule=Host(`neo4j.proof.localhost`)"
            - "traefik.http.routers.neo4j.entrypoints=web"
            - "traefik.http.routers.neo4j.middlewares=redirect@file"

            - "traefik.http.routers.neo4j-secured.service=neo4j"
            - "traefik.http.routers.neo4j-secured.rule=Host(`neo4j.proof.localhost`)"
            - "traefik.http.routers.neo4j-secured.entrypoints=web-secured"
            - "traefik.http.routers.neo4j-secured.tls=true"
            
              # database
            - "traefik.http.services.neo4jdb.loadbalancer.server.port=7687"

            - "traefik.http.routers.neo4jdb.service=neo4jdb"
            - "traefik.http.routers.neo4jdb.rule=Host(`neo4jdb.proof.localhost`)"
            - "traefik.http.routers.neo4jdb.entrypoints=web"
            - "traefik.http.routers.neo4jdb.middlewares=redirect@file"
            
            - "traefik.http.routers.neo4jdb-secured.service=neo4jdb"
            - "traefik.http.routers.neo4jdb-secured.rule=Host(`neo4jdb.proof.localhost`)"
            - "traefik.http.routers.neo4jdb-secured.entrypoints=web-secured"
            - "traefik.http.routers.neo4jdb-secured.tls=true"

            ## tcp
            - "traefik.tcp.services.neo4jdb.loadbalancer.server.port=7687"

            - "traefik.tcp.routers.neo4jdb.service=neo4jdb"
            - "traefik.tcp.routers.neo4jdb.rule=HostSNI(`neo4jdb.proof.localhost`)"
            - "traefik.tcp.routers.neo4jdb.tls=true"
        volumes:
            - neo4j-storage:/data
            - ./neo4j_certs:/ssl
        environment:
            - NEO4J_AUTH=neo4j/admin

            - NEO4J_dbms_connector_bolt_listen__address=neo4j:7687
            - NEO4J_dbms_connector_bolt_advertised__address=neo4jdb.proof.localhost

            - NEO4J_dbms_connector_bolt_tls__level=OPTIONAL

            - NEO4J_dbms_ssl_policy_bolt_enabled=true
            - NEO4J_dbms_ssl_policy_bolt_base__directory=/ssl
            - NEO4J_dbms_ssl_policy_bolt_private__key=neo4j.key
            - NEO4J_dbms_ssl_policy_bolt_public__certificate=neo4j.crt
            - NEO4J_dbms_ssl_policy_bolt_client__auth=NONE
